# Base configs
baseurl: "https://eduardenoiu.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Eduard Enoiu"
subtitle: "The world through my eyes!"
author: "Eduard Enoiu"
header:
 title: "Photography"
 subtitle: "by Eduard Enoiu"
footer:
 name: "Hey there, my name is Edi"
 bio: "I am a researcher and scientist. I live in Västerås with my wife and two jolly little dandie dinmont terriers."
web_design: "AJ"
